services:
  - type: web
    name: whatsapp-integration
    env: node
    plan: standard
    buildCommand: |
      npm install
      apt-get update && apt-get install -y \
        chromium \
        chromium-browser
    startCommand: node socketio.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - socketio.js
        - index.js
        - views/**
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src/token
      sizeGB: 1 