services:
  - type: web
    name: whatsapp-integration
    env: node
    plan: standard
    buildCommand: npm install
    startCommand: node socketio.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - socketio.js
        - index.js
        - views/**
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src/token
      sizeGB: 1 